package GUI;

import bus.GameRoomBUS;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout.Alignment;

public class GameRoomView {
    // GameView.form's Components
    private JPanel contentPane;
    // ViewBinder's components
    private JLabel lblPlayerCount;
    // Others
    private JLabel lblFavor01;
    private JButton btnStartGame;

    private GameRoomBUS gameRoomBUS;
    private JButton btnUpdateInfo;
    private JButton btnQuitGame;
    private JButton btnLeaderBoard;

    public GameRoomView(GameRoomBUS gameRoomBUS) {
        this.gameRoomBUS = gameRoomBUS;

        $$$setupUI$$$();
        customizeComponents();
        bindListeners();
        initViewBinder();
    }

    // Functions

    private void customizeComponents() {
        return;
    }

    private void bindListeners() {
        btnStartGame.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                GameRoomView.this.gameRoomBUS.action_RequestStartGame();
            }
        });
        btnUpdateInfo.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		GameRoomView.this.gameRoomBUS.action_GotoUpdateInfoView();
        	}
        });
    }

    private void initViewBinder() {
        this.gameRoomBUS.viewBinder.lblPlayerCount = lblPlayerCount;
    }

    // Properties

    public JPanel getContentPane() {
        return contentPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setBackground(Color.decode("#35455d"));
        contentPane.setSize(1024, 768);
        lblFavor01 = new JLabel();
        lblFavor01.setFont(new Font("Tahoma", Font.BOLD, 15));
        lblFavor01.setForeground(new Color(-1));
        lblFavor01.setText("Waiting for more players...");
        GridBagConstraints gbc;
        lblPlayerCount = new JLabel();
        lblPlayerCount.setFont(new Font("Tahoma", Font.BOLD, 15));
        lblPlayerCount.setForeground(new Color(-1));
        lblPlayerCount.setText("1/8");
        btnStartGame = new JButton();
        btnStartGame.setFont(new Font("Tahoma", Font.BOLD, 16));
        btnStartGame.setText("Start Game");
        
        btnUpdateInfo = new JButton("Update Info");
        btnUpdateInfo.setFont(new Font("Tahoma", Font.BOLD, 16));
        
        btnQuitGame = new JButton("Quit Game");
        btnQuitGame.setFont(new Font("Tahoma", Font.BOLD, 16));
        
        btnLeaderBoard = new JButton("Leader Board");
        btnLeaderBoard.setFont(new Font("Tahoma", Font.BOLD, 16));
        GroupLayout gl_contentPane = new GroupLayout(contentPane);
        gl_contentPane.setHorizontalGroup(
        	gl_contentPane.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_contentPane.createSequentialGroup()
        			.addGap(410)
        			.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblFavor01, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_contentPane.createSequentialGroup()
        					.addGap(88)
        					.addComponent(lblPlayerCount, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_contentPane.createSequentialGroup()
        					.addGap(32)
        					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(btnStartGame, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnUpdateInfo, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnQuitGame, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnLeaderBoard, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        			.addContainerGap(409, Short.MAX_VALUE))
        );
        gl_contentPane.setVerticalGroup(
        	gl_contentPane.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_contentPane.createSequentialGroup()
        			.addGap(268)
        			.addComponent(lblFavor01)
        			.addGap(16)
        			.addComponent(lblPlayerCount)
        			.addGap(15)
        			.addComponent(btnStartGame)
        			.addGap(16)
        			.addComponent(btnUpdateInfo)
        			.addGap(16)
        			.addComponent(btnQuitGame)
        			.addGap(16)
        			.addComponent(btnLeaderBoard)
        			.addContainerGap(267, Short.MAX_VALUE))
        );
        contentPane.setLayout(gl_contentPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
