package GUI;

import bus.GameRoomBUS;

import javax.swing.*;
import java.awt.*;

public class GameRoomView {
    // GameView.form's Components
    private JPanel contentPane;
    // ViewBinder's components
    private JLabel lblPlayerCount;
    // Others
    private JLabel lblFavor01;
    private JButton btnStartGame;

    private GameRoomBUS gameRoomBUS;

    public GameRoomView(GameRoomBUS gameRoomBUS) {
        this.gameRoomBUS = gameRoomBUS;

        $$$setupUI$$$();
        customizeComponents();
        bindListeners();
        initViewBinder();
    }

    // Functions

    private void customizeComponents() {
        return;
    }

    private void bindListeners() {
    }

    private void initViewBinder() {
        this.gameRoomBUS.viewBinder.lblPlayerCount = lblPlayerCount;
    }

    // Properties

    public JPanel getContentPane() {
        return contentPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        contentPane.setBackground(new Color(-14142061));
        lblFavor01 = new JLabel();
        lblFavor01.setForeground(new Color(-1));
        lblFavor01.setText("Waiting for more players...");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        contentPane.add(lblFavor01, gbc);
        lblPlayerCount = new JLabel();
        lblPlayerCount.setForeground(new Color(-1));
        lblPlayerCount.setText("1/8");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.insets = new Insets(6, 0, 0, 0);
        contentPane.add(lblPlayerCount, gbc);
        btnStartGame = new JButton();
        btnStartGame.setText("Start Game");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.insets = new Insets(16, 0, 0, 0);
        contentPane.add(btnStartGame, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
