package GUI;

import Run.GameMain;
import bus.LoginBUS;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.ConnectException;

public class LoginView {
    /*
      LoginView.form's Components
     */
    private JPanel contentPane;
    // ViewBinder's components
    private JTextField txtUsername;
    private JPasswordField txtPassword;
    private JTextField txtNetIp;
    // Others
    private JLabel lblTitle;
    private JLabel lblUsername;
    private JLabel lblPassword;
    private JButton btnSubmit;
    private JLabel lblNetIp;
    private JPanel formPane;
    private JPanel netPane;
    private JPanel mainPane;
    private JLabel lnkGotoRegister;

    private LoginBUS loginBUS;

    public LoginView(LoginBUS loginBUS) {
        this.loginBUS = loginBUS;

        $$$setupUI$$$();
        customizeComponents();
        bindListeners();
        initViewBinder();
    }

    // Functions

    private void customizeComponents() {
        lnkGotoRegister.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    private void bindListeners() {
        btnSubmit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    LoginView.this.loginBUS.action_LoginSubmit();
                } catch (Exception exception) {
                    String message = exception.getMessage();
                    if (message.contains("Connection refused")) {
                        message = "Game server is currently unavailable.";
                    }

                    JOptionPane.showMessageDialog(
                            LoginView.this.contentPane,
                            message,
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        });

        lnkGotoRegister.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                LoginView.this.loginBUS.action_GotoRegisterView();
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                lnkGotoRegister.setText("<html><a href='' style='color: white'>Create a new account...</a></html>");
            }

            @Override
            public void mouseExited(MouseEvent e) {
                lnkGotoRegister.setText("Create a new account...");
            }
        });
    }

    private void initViewBinder() {
        LoginView.this.loginBUS.viewBinder.txtUsername = txtUsername;
        LoginView.this.loginBUS.viewBinder.txtPassword = txtPassword;
        LoginView.this.loginBUS.viewBinder.txtNetIp = txtNetIp;
    }

    // Properties

    public JPanel getContentPane() {
        return contentPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        contentPane.setBackground(new Color(-14142061));
        contentPane.setPreferredSize(new Dimension(1024, 768));
        mainPane = new JPanel();
        mainPane.setLayout(new GridBagLayout());
        mainPane.setBackground(new Color(-14142061));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        contentPane.add(mainPane, gbc);
        formPane = new JPanel();
        formPane.setLayout(new GridBagLayout());
        formPane.setBackground(new Color(-14142061));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPane.add(formPane, gbc);
        btnSubmit = new JButton();
        btnSubmit.setText("Login");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(8, 0, 0, 0);
        formPane.add(btnSubmit, gbc);
        lblUsername = new JLabel();
        lblUsername.setForeground(new Color(-1));
        lblUsername.setText("Username");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 8, 8);
        formPane.add(lblUsername, gbc);
        lblPassword = new JLabel();
        lblPassword.setForeground(new Color(-1));
        lblPassword.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 8, 8);
        formPane.add(lblPassword, gbc);
        txtPassword = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 120;
        gbc.insets = new Insets(0, 0, 8, 0);
        formPane.add(txtPassword, gbc);
        txtUsername = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 120;
        gbc.insets = new Insets(0, 0, 8, 0);
        formPane.add(txtUsername, gbc);
        lnkGotoRegister = new JLabel();
        lnkGotoRegister.setForeground(new Color(-1));
        lnkGotoRegister.setText("Create a new account...");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(8, 0, 0, 0);
        formPane.add(lnkGotoRegister, gbc);
        lblTitle = new JLabel();
        lblTitle.setFocusCycleRoot(true);
        Font lblTitleFont = this.$$$getFont$$$("Fira Code", Font.BOLD, 32, lblTitle.getFont());
        if (lblTitleFont != null) lblTitle.setFont(lblTitleFont);
        lblTitle.setForeground(new Color(-1));
        lblTitle.setText("NumberFindGame");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 16, 0);
        mainPane.add(lblTitle, gbc);
        netPane = new JPanel();
        netPane.setLayout(new GridBagLayout());
        netPane.setBackground(new Color(-14142061));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.ipady = 10;
        contentPane.add(netPane, gbc);
        lblNetIp = new JLabel();
        Font lblNetIpFont = this.$$$getFont$$$(null, -1, 10, lblNetIp.getFont());
        if (lblNetIpFont != null) lblNetIp.setFont(lblNetIpFont);
        lblNetIp.setForeground(new Color(-1));
        lblNetIp.setText("Server Hostname");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 8);
        netPane.add(lblNetIp, gbc);
        txtNetIp = new JTextField();
        Font txtNetIpFont = this.$$$getFont$$$(null, -1, 10, txtNetIp.getFont());
        if (txtNetIpFont != null) txtNetIp.setFont(txtNetIpFont);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 100;
        netPane.add(txtNetIp, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
