package GUI;

import javax.swing.*;
import java.awt.*;

public class TEST_GameResultPlayerCell {
    private JPanel paneMatchPlayer;
    private JPanel panePlacing;
    private JLabel lblPlacing;
    private JPanel panePlayer;
    private JLabel lblName;
    private JPanel paneScore;
    private JLabel lblScore;
    private JLabel lblInitials;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        paneMatchPlayer = new JPanel();
        paneMatchPlayer.setLayout(new GridBagLayout());
        paneMatchPlayer.setPreferredSize(new Dimension(300, 50));
        panel1.add(paneMatchPlayer);
        panePlacing = new JPanel();
        panePlacing.setLayout(new GridBagLayout());
        panePlacing.setMinimumSize(new Dimension(50, 50));
        panePlacing.setPreferredSize(new Dimension(50, 50));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        paneMatchPlayer.add(panePlacing, gbc);
        lblPlacing = new JLabel();
        Font lblPlacingFont = this.$$$getFont$$$(null, -1, 16, lblPlacing.getFont());
        if (lblPlacingFont != null) lblPlacing.setFont(lblPlacingFont);
        lblPlacing.setText("0th");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panePlacing.add(lblPlacing, gbc);
        panePlayer = new JPanel();
        panePlayer.setLayout(new GridBagLayout());
        panePlayer.setMinimumSize(new Dimension(185, 16));
        panePlayer.setPreferredSize(new Dimension(185, 16));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        paneMatchPlayer.add(panePlayer, gbc);
        lblName = new JLabel();
        lblName.setText("usernameusernam");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panePlayer.add(lblName, gbc);
        lblInitials = new JLabel();
        Font lblInitialsFont = this.$$$getFont$$$(null, -1, 21, lblInitials.getFont());
        if (lblInitialsFont != null) lblInitials.setFont(lblInitialsFont);
        lblInitials.setHorizontalAlignment(0);
        lblInitials.setMinimumSize(new Dimension(56, 16));
        lblInitials.setPreferredSize(new Dimension(56, 16));
        lblInitials.setText("AB");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panePlayer.add(lblInitials, gbc);
        paneScore = new JPanel();
        paneScore.setLayout(new GridBagLayout());
        paneScore.setBackground(new Color(-1));
        paneScore.setMinimumSize(new Dimension(65, 0));
        paneScore.setPreferredSize(new Dimension(65, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        paneMatchPlayer.add(paneScore, gbc);
        lblScore = new JLabel();
        Font lblScoreFont = this.$$$getFont$$$(null, -1, 24, lblScore.getFont());
        if (lblScoreFont != null) lblScore.setFont(lblScoreFont);
        lblScore.setForeground(new Color(-16777216));
        lblScore.setText("10");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        paneScore.add(lblScore, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }
}
